from typing import NamedTuple

from BaseClasses import Location


class DoomEternalLocation(Location):
    game: str = "Doom Eternal"

class LocationData(NamedTuple):
    code: int | None
    region: str

# Base ID for Doom Eternal locations, wanted to do 6660000 but I think that one was used for something else in the past (DOOM 1, DOOM 2), so I went with 7770000 instead. Should be plenty of room for all the locations we need to add.
LOCATION_ID_BASE = 7770000

# Special thanks to TastyFresh from the AP After Dark Discord for helping compile this list of locations.
location_data_table: dict[str, LocationData] = {
    "Hell on Earth - Chainsaw": LocationData(7770001, "Hell on Earth"),
    "Hell on Earth - Heavy Cannon": LocationData(7770002, "Hell on Earth"),
    "Hell on Earth - Frag Grenade": LocationData(7770003, "Hell on Earth"),
    "Hell on Earth - Extra Life - Cliffside in Last Arena": LocationData(7770004, "Hell on Earth"),
    "Hell on Earth - Extra Life - Shopping Center Elevator": LocationData(7770005, "Hell on Earth"),
    "Hell on Earth - Extra Life - Street Arena Behind Breakable Wall": LocationData(7770006, "Hell on Earth"),
    "Hell on Earth - Extra Life - Street Arena Behind Bars": LocationData(7770007, "Hell on Earth"),
    "Hell on Earth - Hell Barges Codex": LocationData(7770008, "Hell on Earth"),
    "Hell on Earth - Remaining Human Populations Part 1 Codex": LocationData(7770009, "Hell on Earth"),
    "Hell on Earth - Remaining Human Populations Part 2 Codex": LocationData(7770010, "Hell on Earth"),
    "Hell on Earth - Formation of the ARC Codex": LocationData(7770011, "Hell on Earth"),
    "Hell on Earth - Hell Priests Codex": LocationData(7770012, "Hell on Earth"),
    "Hell on Earth - Deag Nilox Codex": LocationData(7770013, "Hell on Earth"),
    "Hell on Earth - Modbot 1": LocationData(7770014, "Hell on Earth"),
    "Hell on Earth - Modbot 2": LocationData(7770015, "Hell on Earth"),
    "Hell on Earth - Modbot 3": LocationData(7770016, "Hell on Earth"),
    "Hell on Earth - Zombie Toy": LocationData(7770017, "Hell on Earth"),
    "Hell on Earth - Doom Slayer Toy": LocationData(7770018, "Hell on Earth"),
    "Hell on Earth - Imp Toy": LocationData(7770019, "Hell on Earth"),
    "Hell on Earth - Infinite Extra Lives Cheat": LocationData(7770020, "Hell on Earth"),
    "Hell on Earth - Mission Complete": LocationData(7770122, "Hell on Earth"),

    # left some for exultia here, and deleted all of the rest, but i will place them back here soon
    "Exultia - Blood Punch": LocationData(7770021, "Exultia"),
    "Exultia - Dash": LocationData(7770083, "Exultia"),
    "Exultia - Sentinel Battery": LocationData(7770084, "Exultia"),
    "Exultia - Secret Encounter - Capitol Arena": LocationData(7770089, "Exultia"),
    "Exultia - Secret Encounter - Gore Nest Arena": LocationData(7770090, "Exultia"),
    "Exultia - Slayer Gate Key": LocationData(7770045, "Exultia"),
    "Exultia - Extra Life - Behind King Novik's Throne": LocationData(7770023, "Exultia"),
    "Exultia - Extra Life - Inside Electric Trap": LocationData(7770024, "Exultia"),
    "Exultia - Extra Life - After Dash": LocationData(7770025, "Exultia"),
    "Exultia - Extra Life - Under Level Start": LocationData(7770026, "Exultia"),
    "Exultia - Extra Life - Close to First Rune": LocationData(7770027, "Exultia"),
    "Exultia - Extra Life - Under Floating Platform": LocationData(7770028, "Exultia"),
    "Exultia - Extra Life - Floating in Goo Room": LocationData(7770029, "Exultia"),
    "Exultia - At Doom's Gate Vinyl Record": LocationData(7770030, "Exultia"),
    "Exultia - Arachnotron Toy": LocationData(7770031, "Exultia"),
    "Exultia - Cacodemon Toy": LocationData(7770032, "Exultia"),
    "Exultia - Hidden Plasma Rifle": LocationData(7770034, "Exultia"),
    "Exultia - Sentinel Crystal 1": LocationData(7770035, "Exultia"),
    "Exultia - Exultia Codex Entry": LocationData(7770036, "Exultia"),
    "Exultia - The Wolf Codex Entry": LocationData(7770037, "Exultia"),
    "Exultia - History of the Sentinels Part One Codex Entry": LocationData(7770038, "Exultia"),
    "Exultia - King Novik Codex Entry": LocationData(7770039, "Exultia"),
    "Exultia - History of the Sentinels Part Two Codex Entry": LocationData(7770040, "Exultia"),
    "Exultia - History of the Sentinels Part Three Codex Entry": LocationData(7770041, "Exultia"),
    "Exultia - The Betrayer Codex Entry": LocationData(7770042, "Exultia"),
    "Exultia - Weapon Modbot 1": LocationData(7770043, "Exultia"),
    "Exultia - Rune 1": LocationData(7770044, "Exultia"),
    "Exultia - Mission Complete": LocationData(7770123, "Exultia"),

    # Fortress of Doom
    # The campaign visits the same physical Hub twice during the pre-alpha.
    # Keep only the known mandatory first-visit pickup here. Everything else is
    # conservatively considered second-visit content until room access is mapped.
    "Fortress of Doom - Flame Belch": LocationData(7770073, "Fortress of Doom - First Visit"),
    "Fortress of Doom - Sentinel Crystal 1": LocationData(7770086, "Fortress of Doom - First Visit"),
    "Fortress of Doom - Praetor Suit Token 1": LocationData(7770081, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Fortress of Doom Codex Entry": LocationData(7770072, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Ice Bomb": LocationData(7770074, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Sentinel Crystal 2": LocationData(7770087, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Sentinel Crystal 3": LocationData(7770088, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Praetor Suit Token 2": LocationData(7770163, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Praetor Suit Token 3": LocationData(7770164, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Weapon Modbot 1": LocationData(7770165, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Weapon Modbot 2": LocationData(7770166, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Praetor Suit Token 4": LocationData(7770167, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Praetor Suit Token 5": LocationData(7770168, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - All Runes Cheat Code": LocationData(7770169, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Ballista": LocationData(7770170, "Fortress of Doom - Third Visit"),
    "Fortress of Doom - Fully Upgraded Suit Cheat Code": LocationData(7770171, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Praetor Suit": LocationData(7770253, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Sentinel Armor": LocationData(7770254, "Fortress of Doom - Second Visit"),
    "Fortress of Doom - Classic Marine Suit": LocationData(7770255, "Fortress of Doom - Second Visit"),

    "Cultist Base - Extra Life - Spike Crushers": LocationData(7770046, "Cultist Base"),
    "Cultist Base - Extra Life - After Big Fight Outside": LocationData(7770047, "Cultist Base"),
    "Cultist Base - Extra Life - Before Cultist Key": LocationData(7770048, "Cultist Base"),
    "Cultist Base - Into Sandy's City Vinyl Record": LocationData(7770049, "Cultist Base"),
    "Cultist Base - Gargoyle Toy": LocationData(7770050, "Cultist Base"),
    "Cultist Base - Soldier (Blaster) Toy": LocationData(7770051, "Cultist Base"),
    "Cultist Base - Extra Life - Hanging Cage": LocationData(7770052, "Cultist Base"),
    "Cultist Base - Extra Life - Dopefish 2": LocationData(7770053, "Cultist Base"),
    "Cultist Base - Extra Life - Dopefish 3": LocationData(7770054, "Cultist Base"),
    "Cultist Base - Rocket Launcher": LocationData(7770056, "Cultist Base"),
    "Cultist Base - Sentinel Battery 1": LocationData(7770057, "Cultist Base"),
    "Cultist Base - Sentinel Crystal 1": LocationData(7770058, "Cultist Base"),
    "Cultist Base - IDDQD Cheat Code": LocationData(7770059, "Cultist Base"),
    "Cultist Base - Cultist Base Codex Entry": LocationData(7770060, "Cultist Base"),
    "Cultist Base - Weapon Modbot 1": LocationData(7770061, "Cultist Base"),
    "Cultist Base - Praetor Suit Token 1": LocationData(7770062, "Cultist Base"),
    "Cultist Base - Praetor Suit Token 3": LocationData(7770063, "Cultist Base"),
    "Cultist Base - Praetor Suit Token 4": LocationData(7770064, "Cultist Base"),
    "Cultist Base - Praetor Suit Token 5": LocationData(7770065, "Cultist Base"),
    "Cultist Base - Praetor Suit Token 6": LocationData(7770066, "Cultist Base"),
    "Cultist Base - Rune 2": LocationData(7770067, "Cultist Base"),
    "Cultist Base - Sentinel Battery 2": LocationData(7770069, "Cultist Base"),
    "Cultist Base - Sentinel Battery 3": LocationData(7770070, "Cultist Base"),
    "Cultist Base - Slayer Key": LocationData(7770071, "Cultist Base"),
    "Cultist Base - Mission Complete": LocationData(7770124, "Cultist Base"),
    "Cultist Base - Secret Encounter - Cave Mancubus": LocationData(7770091, "Cultist Base"),
    "Cultist Base - Secret Encounter - Torture Pit": LocationData(7770092, "Cultist Base"),

    "Sticky Bombs - Weapon Mastery Challenge": LocationData(7770125, "Weapon Masteries"),
    "Full Auto - Weapon Mastery Challenge": LocationData(7770126, "Weapon Masteries"),
    "Precision Bolt - Weapon Mastery Challenge": LocationData(7770127, "Weapon Masteries"),
    "Micro Missiles - Weapon Mastery Challenge": LocationData(7770128, "Weapon Masteries"),
    "Heat Blast - Weapon Mastery Challenge": LocationData(7770129, "Weapon Masteries"),
    "Microwave Beam - Weapon Mastery Challenge": LocationData(7770130, "Weapon Masteries"),
    "Lock-on Burst - Weapon Mastery Challenge": LocationData(7770131, "Weapon Masteries"),
    "Remote Detonate - Weapon Mastery Challenge": LocationData(7770132, "Weapon Masteries"),
    "Destroyer Blade - Weapon Mastery Challenge": LocationData(7770133, "Weapon Masteries"),
    "Arbalest - Weapon Mastery Challenge": LocationData(7770134, "Weapon Masteries"),
    "Mobile Turret - Weapon Mastery Challenge": LocationData(7770135, "Weapon Masteries"),
    "Energy Shield - Weapon Mastery Challenge": LocationData(7770136, "Weapon Masteries"),
    "Meat Hook - Weapon Mastery Challenge": LocationData(7770137, "Weapon Masteries"),

    "Cultist Base - Mission Challenge - Pull the Crystal": LocationData(7770138, "Cultist Base"),
    "Cultist Base - Mission Challenge - Armored Rain": LocationData(7770139, "Cultist Base"),
    "Cultist Base - Mission Challenge - Master of Turrets": LocationData(7770140, "Cultist Base"),
    "Doom Hunter Base - Mission Challenge - Musical Interlude": LocationData(7770172, "Doom Hunter Base"),
    "Doom Hunter Base - Mission Challenge - Big Reveal": LocationData(7770173, "Doom Hunter Base"),
    "Doom Hunter Base - Mission Challenge - Fire in the Hole": LocationData(7770174, "Doom Hunter Base"),
    "Super Gore Nest - Mission Challenge - Weaponslave": LocationData(7770206, "Super Gore Nest"),
    "Super Gore Nest - Mission Challenge - A Bloody Secret": LocationData(7770207, "Super Gore Nest"),
    "Super Gore Nest - Mission Challenge - War Pinkies": LocationData(7770208, "Super Gore Nest"),
    "Cultist Base - All Mission Challenges Completed": LocationData(7770141, "Cultist Base"),
    "Doom Hunter Base - All Mission Challenges Completed": LocationData(7770175, "Doom Hunter Base"),

    # Doom Hunter Base
    "Doom Hunter Base - Extra Life - Opening": LocationData(7770143, "Doom Hunter Base"),
    "Doom Hunter Base - Praetor Suit Token 1": LocationData(7770144, "Doom Hunter Base"),
    "Doom Hunter Base - Deag Ranak Codex": LocationData(7770145, "Doom Hunter Base"),
    "Doom Hunter Base - Doom Hunter Base Codex": LocationData(7770146, "Doom Hunter Base"),
    "Doom Hunter Base - Doom Hunter Codex": LocationData(7770147, "Doom Hunter Base"),
    "Doom Hunter Base - Sentinel Battery 1": LocationData(7770148, "Doom Hunter Base"),
    "Doom Hunter Base - Praetor Suit Token 2": LocationData(7770149, "Doom Hunter Base"),
    "Doom Hunter Base - Extra Life - Furnace": LocationData(7770150, "Doom Hunter Base"),
    "Doom Hunter Base - Sentinel Battery 2": LocationData(7770151, "Doom Hunter Base"),
    "Doom Hunter Base - Sentinel Crystal": LocationData(7770152, "Doom Hunter Base"),
    "Doom Hunter Base - Extra Life - Moving Platform": LocationData(7770153, "Doom Hunter Base"),
    "Doom Hunter Base - Weapon Modbot": LocationData(7770154, "Doom Hunter Base"),
    "Doom Hunter Base - Praetor Suit Token 3": LocationData(7770155, "Doom Hunter Base"),
    "Doom Hunter Base - Hell Knight Toy": LocationData(7770156, "Doom Hunter Base"),
    "Doom Hunter Base - Keen - Shadows Don't Scare Commander Keen Vinyl": LocationData(7770157, "Doom Hunter Base"),
    "Doom Hunter Base - Praetor Suit Token 4": LocationData(7770158, "Doom Hunter Base"),
    "Doom Hunter Base - Silver Bullet Mode Cheat Code": LocationData(7770159, "Doom Hunter Base"),
    "Doom Hunter Base - Lost Soul Toy": LocationData(7770160, "Doom Hunter Base"),
    "Doom Hunter Base - Rune": LocationData(7770161, "Doom Hunter Base"),
    "Doom Hunter Base - Mission Complete": LocationData(7770162, "Doom Hunter Base"),

    # Super Gore Nest
    "Super Gore Nest - Praetor Suit Token 1": LocationData(7770176, "Super Gore Nest"),
    "Super Gore Nest - Praetor Suit Token 2": LocationData(7770177, "Super Gore Nest"),
    "Super Gore Nest - Praetor Suit Token 3": LocationData(7770178, "Super Gore Nest"),
    "Super Gore Nest - Praetor Suit Token 4": LocationData(7770179, "Super Gore Nest"),
    "Super Gore Nest - Praetor Suit Token 5": LocationData(7770180, "Super Gore Nest"),
    "Super Gore Nest - Weapon Modbot 1": LocationData(7770181, "Super Gore Nest"),
    "Super Gore Nest - Weapon Modbot 2": LocationData(7770182, "Super Gore Nest"),
    "Super Gore Nest - Rune 1": LocationData(7770183, "Super Gore Nest"),
    "Super Gore Nest - Rune 2": LocationData(7770184, "Super Gore Nest"),
    "Super Gore Nest - Soldier (Shield) Toy": LocationData(7770185, "Super Gore Nest"),
    "Super Gore Nest - Revenant Toy": LocationData(7770186, "Super Gore Nest"),
    "Super Gore Nest - Mecha Zombie Toy": LocationData(7770187, "Super Gore Nest"),
    "Super Gore Nest - Doom 3 - Main Theme Vinyl": LocationData(7770188, "Super Gore Nest"),
    "Super Gore Nest - Wolf 3D - Wondering About My Loved Ones Vinyl": LocationData(7770189, "Super Gore Nest"),
    "Super Gore Nest - Extra Life 1": LocationData(7770190, "Super Gore Nest"),
    "Super Gore Nest - Extra Life 2": LocationData(7770191, "Super Gore Nest"),
    "Super Gore Nest - Extra Life 3": LocationData(7770192, "Super Gore Nest"),
    "Super Gore Nest - Extra Life 4": LocationData(7770193, "Super Gore Nest"),
    "Super Gore Nest - The Hellgrowth Part I Codex": LocationData(7770194, "Super Gore Nest"),
    "Super Gore Nest - The Hellgrowth Part II Codex": LocationData(7770195, "Super Gore Nest"),
    "Super Gore Nest - Super Gore Nest Codex": LocationData(7770196, "Super Gore Nest"),
    "Super Gore Nest - Sentinel Battery 1": LocationData(7770197, "Super Gore Nest"),
    "Super Gore Nest - Sentinel Battery 2": LocationData(7770198, "Super Gore Nest"),
    "Super Gore Nest - Sentinel Battery 3": LocationData(7770199, "Super Gore Nest"),
    "Super Gore Nest - Infinite Ammo Cheat Code": LocationData(7770200, "Super Gore Nest"),
    "Super Gore Nest - Chaingun": LocationData(7770201, "Super Gore Nest"),
    "Super Gore Nest - Secret Encounter 1": LocationData(7770202, "Super Gore Nest"),
    "Super Gore Nest - Secret Encounter 2": LocationData(7770203, "Super Gore Nest"),
    "Super Gore Nest - Sentinel Crystal": LocationData(7770204, "Super Gore Nest"),
    "Super Gore Nest - Slayer Key": LocationData(7770205, "Super Gore Nest"),
    "Super Gore Nest - All Mission Challenges Completed": LocationData(7770209, "Super Gore Nest"),
    "Super Gore Nest - Mission Complete": LocationData(7770210, "Super Gore Nest"),
    "Fortress of Doom - Super Gore Nest Transition": LocationData(None, "Fortress of Doom - Third Visit"),

    # ARC Complex
    "ARC Complex - Praetor Suit Token 1": LocationData(7770211, "ARC Complex"),
    "ARC Complex - Praetor Suit Token 2": LocationData(7770212, "ARC Complex"),
    "ARC Complex - Praetor Suit Token 3": LocationData(7770213, "ARC Complex"),
    "ARC Complex - Praetor Suit Token 4": LocationData(7770214, "ARC Complex"),
    "ARC Complex - Praetor Suit Token 5": LocationData(7770215, "ARC Complex"),
    "ARC Complex - Weapon Modbot 1": LocationData(7770216, "ARC Complex"),
    "ARC Complex - Weapon Modbot 2": LocationData(7770217, "ARC Complex"),
    "ARC Complex - Sentinel Battery 1": LocationData(7770218, "ARC Complex"),
    "ARC Complex - Sentinel Battery 2": LocationData(7770219, "ARC Complex"),
    "ARC Complex - Sentinel Battery 3": LocationData(7770220, "ARC Complex"),
    "ARC Complex - Rune 1": LocationData(7770221, "ARC Complex"),
    "ARC Complex - Rune 2": LocationData(7770222, "ARC Complex"),
    "ARC Complex - Extra Life 1": LocationData(7770223, "ARC Complex"),
    "ARC Complex - Extra Life 2": LocationData(7770224, "ARC Complex"),
    "ARC Complex - Extra Life 3": LocationData(7770225, "ARC Complex"),
    "ARC Complex - Mancubus Toy": LocationData(7770226, "ARC Complex"),
    "ARC Complex - Whiplash Toy": LocationData(7770227, "ARC Complex"),
    "ARC Complex - Cueball Toy": LocationData(7770228, "ARC Complex"),
    "ARC Complex - Into Sandy's City Vinyl Record": LocationData(7770229, "ARC Complex"),
    "ARC Complex - The Demonic Horde Vinyl Record": LocationData(7770230, "ARC Complex"),
    "ARC Complex - IDKFA Cheat Code": LocationData(7770231, "ARC Complex"),
    "ARC Complex - The ARC - Part 1 Codex": LocationData(7770232, "ARC Complex"),
    "ARC Complex - The ARC - Part 2 Codex": LocationData(7770233, "ARC Complex"),
    "ARC Complex - Samuel Hayden Codex": LocationData(7770234, "ARC Complex"),
    "ARC Complex - Return of Dr. Hayden - Part 1 Codex": LocationData(7770235, "ARC Complex"),
    "ARC Complex - Return of Dr. Hayden - Part 2 Codex": LocationData(7770236, "ARC Complex"),
    "ARC Complex - Slayer Key": LocationData(7770237, "ARC Complex"),
    "ARC Complex - Sentinel Crystal": LocationData(7770240, "ARC Complex"),
    "ARC Complex - Secret Encounter 1": LocationData(7770242, "ARC Complex"),
    "ARC Complex - Secret Encounter 2": LocationData(7770243, "ARC Complex"),
    "ARC Complex - Mission Challenge - Rune Finder": LocationData(7770244, "ARC Complex"),
    "ARC Complex - Mission Challenge - External Combustion": LocationData(7770245, "ARC Complex"),
    "ARC Complex - Mission Challenge - Solitary Confinement": LocationData(7770246, "ARC Complex"),
    "ARC Complex - All Mission Challenges Completed": LocationData(7770247, "ARC Complex"),
    "ARC Complex - Mission Complete": LocationData(7770248, "ARC Complex"),
    "ARC Complex - Dr. Elena Richardson Log 1": LocationData(7770249, "ARC Complex"),
    "ARC Complex - Dr. Elena Richardson Log 2": LocationData(7770250, "ARC Complex"),
    "ARC Complex - Dr. Elena Richardson Log 3": LocationData(7770251, "ARC Complex"),
    "ARC Complex - Dr. Elena Richardson Log 4": LocationData(7770252, "ARC Complex"),
    # Mars Core
    "Mars Core - Praetor Suit Token 1": LocationData(7770256, "Mars Core"),
    "Mars Core - Praetor Suit Token 2": LocationData(7770257, "Mars Core"),
    "Mars Core - Praetor Suit Token 3": LocationData(7770258, "Mars Core"),
    "Mars Core - Praetor Suit Token 4": LocationData(7770259, "Mars Core"),
    "Mars Core - Praetor Suit Token 5": LocationData(7770260, "Mars Core"),
    "Mars Core - Sentinel Battery 1": LocationData(7770261, "Mars Core"),
    "Mars Core - Sentinel Battery 2": LocationData(7770262, "Mars Core"),
    "Mars Core - Sentinel Battery 3": LocationData(7770263, "Mars Core"),
    "Mars Core - Rune 1": LocationData(7770264, "Mars Core"),
    "Mars Core - Rune 2": LocationData(7770265, "Mars Core"),
    "Mars Core - Extra Life 1": LocationData(7770266, "Mars Core"),
    "Mars Core - Extra Life 2": LocationData(7770267, "Mars Core"),
    "Mars Core - Extra Life 3": LocationData(7770268, "Mars Core"),
    "Mars Core - Extra Life 4": LocationData(7770269, "Mars Core"),
    "Mars Core - Extra Life 5": LocationData(7770270, "Mars Core"),
    "Mars Core - Extra Life 6": LocationData(7770271, "Mars Core"),
    "Mars Core - Prowler Toy": LocationData(7770272, "Mars Core"),
    "Mars Core - Carcass Toy": LocationData(7770273, "Mars Core"),
    "Mars Core - Pinky Toy": LocationData(7770274, "Mars Core"),
    "Mars Core - DOOM 64 - Main Theme Vinyl Record": LocationData(7770275, "Mars Core"),
    "Mars Core - Quake Champions - Goroth Vinyl Record": LocationData(7770276, "Mars Core"),
    "Mars Core - Infinite Onslaught Cheat Code": LocationData(7770277, "Mars Core"),
    "Mars Core - BFG-10000 Codex": LocationData(7770278, "Mars Core"),
    "Mars Core - Lost City of Hebeth Codex": LocationData(7770279, "Mars Core"),
    "Mars Core - Slayer Key": LocationData(7770280, "Mars Core"),
    "Mars Core - Sentinel Crystal": LocationData(7770281, "Mars Core"),
    # 7770282 is deferred for future BFG-9000 randomization; do not reuse.
    "Mars Core - Secret Encounter 1": LocationData(7770283, "Mars Core"),
    "Mars Core - Secret Encounter 2": LocationData(7770284, "Mars Core"),
    "Mars Core - Mission Challenge - Big Ba-Da Boom": LocationData(7770285, "Mars Core"),
    "Mars Core - Mission Challenge - Disarmament": LocationData(7770286, "Mars Core"),
    "Mars Core - Mission Challenge - Lock and Key": LocationData(7770287, "Mars Core"),
    "Mars Core - All Mission Challenges Completed": LocationData(7770288, "Mars Core"),
    "Mars Core - Mission Complete": LocationData(7770289, "Mars Core"),
    "Mars Core - Sentinel Prime Transition": LocationData(None, "Mars Core"),
}
location_name_to_id = {
    name: data.code for name, data in location_data_table.items()
    if data.code is not None
}
