"""Project release/version.json into APWorld and optional mod checkout."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
VERSION_PATH = ROOT / "release" / "version.json"
WORLD_DIR = Path(__file__).resolve().parent


def _render_python(version: dict) -> str:
    return "\n".join((
        '"""GENERATED by worlds.doometernal.sync_version; do not edit."""',
        "",
        f"PUBLIC_VERSION = {version['public_version']!r}",
        f"GAME_NAME = {version['game']!r}",
        f"APWORLD_REVISION = {version['apworld_revision']!r}",
        f"CONTENT_REVISION = {version['content_revision']!r}",
        f"BRIDGE_PROTOCOL = {version['bridge_protocol']!r}",
        f"CONTENT_SCHEMA = {version['content_schema']!r}",
        f"COMPILER_REVISION = {version['compiler_revision']!r}",
        "",
    ))


def _render_manifest(version: dict) -> str:
    return json.dumps({
        "game": version["game"],
        "authors": ["snow"],
        "world_version": version["public_version"].split("-", 1)[0],
        "release_label": version["public_version"],
        "minimum_ap_version": "0.6.7",
    }, indent=2) + "\n"


def _render_mod_identity(version: dict) -> str:
    return json.dumps({
        "bridge_protocol_version": version["bridge_protocol"],
        "apworld_revision": version["apworld_revision"],
        "compiler_revision": version["compiler_revision"],
        "content_revision": version["content_revision"],
        "content_schema_version": version["content_schema"],
        "game": version["game"],
        "release_version": version["public_version"],
    }, indent=2, sort_keys=True) + "\n"


def _write(path: Path, payload: str, check: bool) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == payload:
        return
    if check:
        raise ValueError(f"stale version projection: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8", newline="\n")


def sync(*, check: bool, mod_root: Path | None = None) -> None:
    version = json.loads(VERSION_PATH.read_text(encoding="utf-8"))
    required = {"public_version", "game", "apworld_revision", "content_revision", "bridge_protocol", "content_schema", "compiler_revision"}
    missing = required - version.keys()
    if missing:
        raise ValueError(f"release/version.json missing: {', '.join(sorted(missing))}")
    _write(WORLD_DIR / "version.py", _render_python(version), check)
    _write(WORLD_DIR / "archipelago.json", _render_manifest(version), check)
    if mod_root is not None:
        _write(mod_root / "data" / "content_identity.json", _render_mod_identity(version), check)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--mod-root", type=Path)
    args = parser.parse_args()
    sync(check=args.check, mod_root=args.mod_root)


if __name__ == "__main__":
    main()
