"""GENERATED by worlds.doometernal.sync_version; do not edit."""

PUBLIC_VERSION = '0.4.0-beta.1'
GAME_NAME = 'DOOM Eternal'
APWORLD_REVISION = '0.4.0-beta.1'
CONTENT_REVISION = '0.4.0-beta.1'
BRIDGE_PROTOCOL = 4
CONTENT_SCHEMA = 3
COMPILER_REVISION = 1
